model_options:
  test_size: 0.2
  random_state: 42
  target: Outcome
  features:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age

kmeans:
  n_clusters: 3

unsupervised_learning:
  features:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  pca:
    n_components: 3
  clustering:
    n_clusters: 4
    random_state: 42
  anomalies:
    contamination: 0.07
    random_state: 42