# ============================================================
# Parámetros del pipeline de ciencia de datos (data_science)
# ============================================================

data_science_model_options:
  # Columnas (features) que se usarán como variables independientes
  features:
    - passenger_capacity
    - crew
    - fuel_capacity
    - price  # ⚠️ si "price" es el target, elimínalo de esta lista

  # Variable dependiente o target (valor continuo para regresión)
  target: price

  # Porcentaje de datos usados para testeo
  test_size: 0.2

  # Semilla aleatoria para reproducibilidad
  random_state: 42

  # Lista de modelos a entrenar
  models:
    - LinearRegression
    - Ridge
    - Lasso
    - RandomForestRegressor
    - GradientBoostingRegressor

  # Hiperparámetros básicos para cada modelo
  hyperparameters:
    Ridge:
      alpha: 1.0
    Lasso:
      alpha: 0.1
    RandomForestRegressor:
      n_estimators: 100
      random_state: 42
    GradientBoostingRegressor:
      n_estimators: 100
      learning_rate: 0.1
      random_state: 42

# ============================
# ⚙️ PARÁMETROS DE DIABETES
# ============================

diabetes_model_options:
  test_size: 0.2
  random_state: 42
  target_column: Diabetes_binary
  models:
    logistic_regression:
      type: logistic
    random_forest:
      type: random_forest
      n_estimators: 100
      max_depth: 5
